language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install --upgrade pip
  - pip --version
  - pip install --upgrade setuptools
  - pip install tox tox-travis coveralls
script:
  - tox
after_success:
  - coveralls
